version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: testrun-backend
    restart: unless-stopped
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
      - sqlite-data:/app/prisma
    depends_on: []

  frontend:
    build:
      context: ./frontend
    container_name: testrun-frontend
    restart: unless-stopped
    environment:
      BACKEND_URL: http://backend:3000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

volumes:
  sqlite-data:
